/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_spk;

import java.sql.*;
import Connection.koneksi;
import Login.login_spk;
import Login.regist_spk;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class main_menu extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    public static String nama;
    

    public main_menu() {
        initComponents();
        txtnmlngkp.setText(regist_spk.getnama());
        String KD = UserID.getUserLogin();
        txtnmlngkp.setText(KD);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bexit = new javax.swing.JButton();
        bsiswa = new javax.swing.JButton();
        bkriteria = new javax.swing.JButton();
        txtnmlngkp = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bhome = new javax.swing.JButton();
        bperhitungan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        bjurusan = new javax.swing.JButton();
        badmin = new javax.swing.JButton();
        bbobot = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(240, 189, 108));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(34, 105, 54));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 20, 50));

        bexit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        bexit.setText("  Keluar");
        bexit.setBorder(null);
        bexit.setBorderPainted(false);
        bexit.setContentAreaFilled(false);
        bexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bexit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel2.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 170, 50));

        bsiswa.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        bsiswa.setText("  Data Siswa");
        bsiswa.setBorder(null);
        bsiswa.setBorderPainted(false);
        bsiswa.setContentAreaFilled(false);
        bsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsiswaActionPerformed(evt);
            }
        });
        jPanel2.add(bsiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, 50));

        bkriteria.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        bkriteria.setText("  Data Kriteria");
        bkriteria.setBorder(null);
        bkriteria.setBorderPainted(false);
        bkriteria.setContentAreaFilled(false);
        bkriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkriteria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkriteriaActionPerformed(evt);
            }
        });
        jPanel2.add(bkriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 50));

        txtnmlngkp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtnmlngkp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnmlngkp.setText("Nama Lengkap User");
        jPanel2.add(txtnmlngkp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 190, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bhome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        bhome.setText("  Beranda");
        bhome.setBorder(null);
        bhome.setBorderPainted(false);
        bhome.setContentAreaFilled(false);
        bhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });
        jPanel3.add(bhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, 50));

        bperhitungan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        bperhitungan.setText("  Perhitungan");
        bperhitungan.setBorder(null);
        bperhitungan.setBorderPainted(false);
        bperhitungan.setContentAreaFilled(false);
        bperhitungan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bperhitungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bperhitungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bperhitunganActionPerformed(evt);
            }
        });
        jPanel2.add(bperhitungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home_100px.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 10, -1, 90));

        bjurusan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        bjurusan.setText("  Data Jurusan");
        bjurusan.setBorder(null);
        bjurusan.setBorderPainted(false);
        bjurusan.setContentAreaFilled(false);
        bjurusan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bjurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjurusanActionPerformed(evt);
            }
        });
        jPanel2.add(bjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, 50));

        badmin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        badmin.setText("  Data Admin");
        badmin.setBorder(null);
        badmin.setBorderPainted(false);
        badmin.setContentAreaFilled(false);
        badmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        badmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        badmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badminActionPerformed(evt);
            }
        });
        jPanel2.add(badmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 170, 50));

        bbobot.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        bbobot.setText("  Data Bobot");
        bbobot.setBorder(null);
        bbobot.setBorderPainted(false);
        bbobot.setContentAreaFilled(false);
        bbobot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbobot.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bbobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbobotActionPerformed(evt);
            }
        });
        jPanel2.add(bbobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 170, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 530));

        jPanel5.setBackground(new java.awt.Color(240, 39, 45));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SMK PGRI 28 JAKARTA");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 480, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TERAMPIL, MANDIRI DAN TAQWA");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 380, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("V I S I  D A N  M I S I");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Yang Maha Esa");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 380, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TERBENTUKNYA TENAGA MENENGAH");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VISI");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 380, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MISI");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 380, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("mandiri");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 380, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("1. Meningkatkan tenaga kerja yang taqwa kepada Tuhan");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 380, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("2. Memantapkan keterampilan siswa menuju Insan yang ");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 380, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("aman dan nyaman");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 380, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("prasarana agar terbentuk kompetensi dasar yang kuat");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 380, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("3. Mengembangkan dan mengoptimalkan sarana");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 380, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("berakhlak mulia");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 380, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("4. Mengkondisikan lingkungan sekolah yg sehat, bersih, ");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 380, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("5. Membangun jiwa wirausaha yang handal dan");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 380, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("6. Meningkatkan kerja sama dengan dunia usaha dan");
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 380, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("dunia industri dalam bentuk praktek kerja lapangan");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 380, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 380, 380));

        jPanel6.setBackground(new java.awt.Color(243, 248, 25));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("2. Otomatisasi Tata Kelola Perkantoran");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 380, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("TERAKREDITASI \"A\"");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 380, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Program Keahliah :");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 380, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Bisnis dan Manajemen");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 380, -1));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/instagram_20px.png"))); // NOI18N
        jLabel26.setText("@officialsmk28");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 380, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("1. Akuntansi dan Keuangan Lembaga");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 380, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 340, 10));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Kompetensi Keahlian : ");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 380, -1));

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Jalan Raya Condet - Gedong");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 380, -1));

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Pasar Rebo, Jakarta Timur");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 380, -1));

        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/phone_20px.png"))); // NOI18N
        jLabel31.setText("021 - 8414029");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 380, -1));

        jLabel32.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/envelope_20px.png"))); // NOI18N
        jLabel32.setText("smk_pgri28jkt@yahoo.com");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 380, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("SMK PGRI 28 JAKARTA");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 380, 380));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PGRI.CLR150.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SISTEM PENUNJANG KEPUTUSAN SISWA BERPRESTASI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 1120, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("SMK PGRI 28 JAKARTA");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 1120, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("     \"Data Bobot\" ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 340, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Langkah Penggunaan Aplikasi :");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 340, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel35.setText("    \"Data Siswa\"");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 340, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel36.setText("1. Tentukan nilai bobot kriteria pada menu");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 340, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel37.setText("2. Input data diri siswa pada menu ");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 340, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel38.setText("3. Input data nilai kriteria pada menu");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 340, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel39.setText("    \"Data Kriteria\"");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 340, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel44.setText("4. Lakukan perhitungan di menu \"Perhitungan\".");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 340, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel45.setText("    Kemudian klik button \"Hitung yang ada di");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 340, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel46.setText("    bawah tabel Normalisasi dan Peringkat");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 310, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel48.setText("5. Klik button \"Tampil\" pada menu \"Perhitungan\".");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 340, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel49.setText("    button \"Delete All\", kemudian klik \"Simpan\"");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 340, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel50.setText("    Laluklik button \"Tampil\" pada form Pop Up. ");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 340, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel53.setText("    Pastikan database kosong dengan mengklik");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 340, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 530));

        setSize(new java.awt.Dimension(1327, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
        
    }//GEN-LAST:event_bhomeActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        int tny = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar ?","Tanya",JOptionPane.YES_NO_OPTION);
        if (tny==0) {     
            try {
                dispose();
                
            } catch (Exception e) {
            }
        }
        new Login.login_spk().setVisible(true);
    }//GEN-LAST:event_bexitActionPerformed

    private void bsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsiswaActionPerformed
        form_dataSiswa siswa;
        siswa = new form_dataSiswa();
        siswa.setVisible(true);
        dispose();
    }//GEN-LAST:event_bsiswaActionPerformed

    private void bkriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkriteriaActionPerformed
        form_dataKriteria kriteria;
        kriteria = new form_dataKriteria();
        kriteria.setVisible(true);
        dispose();
    }//GEN-LAST:event_bkriteriaActionPerformed

    private void bperhitunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bperhitunganActionPerformed
        form_perhitungan perhitungan;
        perhitungan = new form_perhitungan();
        perhitungan.setVisible(true);
        dispose();
    }//GEN-LAST:event_bperhitunganActionPerformed

    private void bbobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbobotActionPerformed
        form_dataBobot bobot;
        bobot = new form_dataBobot();
        bobot.setVisible(true);
        dispose();
    }//GEN-LAST:event_bbobotActionPerformed

    private void bjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjurusanActionPerformed
        form_dataJurusan jurusan;
        jurusan = new form_dataJurusan();
        jurusan.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bjurusanActionPerformed

    private void badminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badminActionPerformed
        form_dataAdmin admin;
        admin = new form_dataAdmin();
        admin.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_badminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badmin;
    private javax.swing.JButton bbobot;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bhome;
    private javax.swing.JButton bjurusan;
    private javax.swing.JButton bkriteria;
    private javax.swing.JButton bperhitungan;
    private javax.swing.JButton bsiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel txtnmlngkp;
    // End of variables declaration//GEN-END:variables
}
